"""empty message

Revision ID: cf26b31f271d
Revises: 523f79fa675f
Create Date: 2025-11-22 02:42:48.368928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf26b31f271d'
down_revision = '523f79fa675f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=12), nullable=False),
    sa.Column('goal', sa.String(length=10), nullable=False),
    sa.Column('restrictions', sa.Text(), nullable=True),
    sa.Column('calories_target', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('menu', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('diet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('activity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('goal', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('calories', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('protein', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('carbs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fat', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('breakfast', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('lunch', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('dinner', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('snacks', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('diet_pkey'))
    )
    op.drop_table('diet_plans')
    # ### end Alembic commands ###
